// Code generated by mockery v2.16.0. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/alvadorn/people-api/components/people/domain"
	"github.com/stretchr/testify/mock"
)

// apiClientPeopleOperatorMock is an autogenerated mock type for the apiClientPeopleOperatorMock type
type apiClientPeopleOperatorMock struct {
	mock.Mock
}

// getByName provides a mock function with given fields: ctx, name
func (_m *apiClientPeopleOperatorMock) getByName(ctx context.Context, name string) (*domain.Person, error) {
	ret := _m.Called(ctx, name)

	var r0 *domain.Person
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Person); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Person)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTnewApiClientPeopleOperator interface {
	mock.TestingT
	Cleanup(func())
}

// newApiClientPeopleOperator creates a new instance of apiClientPeopleOperatorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newApiClientPeopleOperator(t mockConstructorTestingTnewApiClientPeopleOperator) *apiClientPeopleOperatorMock {
	mock := &apiClientPeopleOperatorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
